Genepop 4.7.0: Hardy-Weinberg test

File: pop0.txt (Outputted by simuPOP at Wed, 06 Jun 2018 07:17:09)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-100
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.7836  0.0043  -0.0576 -0.0579  84240 switches
partial     0.2899  0.0070   0.0782  0.0786  83700 switches

Normal ending
