Genepop 4.7.0: Hardy-Weinberg test

File: pop9.txt (Outputted by simuPOP at Wed, 06 Jun 2018 07:17:10)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-100
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0000  0.0000   0.7606  0.7673  84042 switches
partial     0.0000  0.0000   0.6628  0.6683  84200 switches

Normal ending
