Genepop 4.7.0: Hardy-Weinberg test

File: pop2.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:10:02)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9045  0.0080  -0.0385 -0.0385  94926 switches
qPh2        0.7290  0.0168  -0.0151 -0.0151  94839 switches

Normal ending
