Genepop 4.7.0: Hardy-Weinberg test

File: pop8.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:10:03)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9933  0.0018  -0.0719 -0.0720  94870 switches
qPh2        0.9990  0.0004  -0.0810 -0.0810  94901 switches

Normal ending
