Genepop 4.7.0: Hardy-Weinberg test

File: pop9.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:10:03)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1581  0.0121   0.0345  0.0345  94824 switches
qPh2        0.7450  0.0162  -0.0167 -0.0167  94781 switches

Normal ending
