Genepop 4.7.0: Hardy-Weinberg test

File: pop2.txt (Outputted by simuPOP at Wed, 06 Jun 2018 08:23:12)

Number of populations detected:    1
Number of loci detected:           1


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-100
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0000  0.0000   1.0000  1.0101  79871 switches

Normal ending
