Genepop 4.7.0: Hardy-Weinberg test

File: pop9.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:54:49)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0000  0.0000   0.2850  0.2852  94895 switches
qPh2        0.0000  0.0000   0.3604  0.3607  94921 switches

Normal ending
