Genepop 4.7.0: Hardy-Weinberg test

File: pop6.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:55:13)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.9741  0.0039  -0.0568 -0.0568  94941 switches
qPh2        0.9594  0.0063  -0.0496 -0.0497  94932 switches

Normal ending
