Genepop 4.7.0: Hardy-Weinberg test

File: pop7.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:55:14)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.5772  0.0155  -0.0041 -0.0041  94941 switches
qPh2        0.0313  0.0067   0.0627  0.0627  94932 switches

Normal ending
