Genepop 4.7.0: Hardy-Weinberg test

File: pop8.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:55:16)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.1513  0.0114   0.0355  0.0355  94877 switches
qPh2        0.7222  0.0171  -0.0146 -0.0146  94885 switches

Normal ending
