Genepop 4.7.0: Hardy-Weinberg test

File: pop6.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:10:03)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : SubPop0-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        1.0000  0.0000  -0.1070 -0.1070  94592 switches
qPh2        0.3437  0.0194   0.0179  0.0179  94347 switches

Normal ending
