Genepop 4.7.0: Hardy-Weinberg test

File: pop1.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:52:31)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0000  0.0000   0.4518  0.4521  94949 switches
qPh2        0.0000  0.0000   0.5083  0.5087  94923 switches

Normal ending
