Genepop 4.7.0: Hardy-Weinberg test

File: pop3.txt (Outputted by simuPOP at Wed, 06 Jun 2018 13:55:10)

Number of populations detected:    1
Number of loci detected:           2


Estimation of exact P-Values by the Markov chain method. 
---------------------------------------------
Markov chain parameters for all tests:
Dememorization:              10000
Batches:                     20
Iterations per batch:        5000
Hardy Weinberg test when H1= heterozygote deficit
                         ************************



==========================================
     Results by population
==========================================


Pop : test-1000
-----------------------------------------
                             Fis estimates
                            ---------------
locus       P-val   S.E.    W&C     R&H     Steps 
----------- ------- ------- ------- ------- ------
qPh1        0.0806  0.0083   0.0455  0.0455  94965 switches
qPh2        0.0174  0.0049   0.0684  0.0685  94919 switches

Normal ending
